### ISSUE TITLE
Not reverse complimenting the strand when it should

### ISSUE THREAD

**Issue by nadiadavidson** [Oshlack/Lace#20]
I think lace still isn't handling the strand properly. e.g. see RECK in /mnt/storage/nadiad/work_area/20160203_ALL/simulation/SIM/lace on our server
input files are all.fasta and all.groupings
in /mnt/storage/nadiad/work_area/20160203_ALL/simulation/SIM

lace was installed using conda instructions on the wiki.

**Comment by Quarkins** [comment]
Thanks Nadia, will check this out and see what is going on :)
