### ISSUE TITLE
Problem with memory exceeding the limit.

### ISSUE THREAD

**Issue by nadiadavidson** [Oshlack/Lace#29]
Problem reported by user over email.
Appears to be a single cluster that uses all the memory.
User sent data and the problem was reproduced. We need to investigate Cluster-16676.1839

**Comment by nadiadavidson** [comment]
I tracked the problem down to the networkX package function simple_cycles() which uses excessive time and RAM for highly complex graphs. A possible solution would be to time this function and kill it if some limits are exceeded then report just the longest contig, or use some other function to find cycles which behaves better.

**Comment by Quarkins** [comment]
Right, that is what i might have guessed. Finding cycles in complex graphs is apparently non trivial, this is usually the bottle neck to most of the lacing which take time. I thought about implementing another algorithm but in python i doubt it would be faster, i reckon in some graphs it is probably too messy/complex so i would opt for the kill it if it takes too long and choose the longest contig. Even if we did succesfully and efficiently find all the cycles breaking it would be non trivial and such a messy graph is probably indicative of poor assembly or clustering. Are you happy to implement the changes or else i can do it when i get some good internet and time?

**Comment by nadiadavidson** [comment]
I think part of the problem is that simple_cyles() reports all possible cycles, when probably we just need the minimum set or do we need all? The other library functions don't seem to be applicable to directed graphs, so probably not trivial to use.

I agree that it probably makes more sense to time-out the function and report the longest contig. I did a quick google and it looks like there are some issues with threads when you try to monitor the function to time-out, but I'm no python expert. Happy for either of us to implement. I don't think there's a rush for this as it's a rare occurrence.

**Comment by nadiadavidson** [comment]
Fixed by checking the number of edges before calling the function to finding cycles. More than 100 edges (?) and Lace gives up and reports the longest isoform.
