### ISSUE TITLE
Question: use SuperTranscripts for paralogs 

### ISSUE THREAD

**Issue by hydrahamster** [Oshlack/Lace#33]
Hi there,

Lace & superTranscripts sounds excellent for non-model organisms without a reference genome.  I'd love to try it.  Though the application would be slightly different. I think it may still work but would like your opinion. 
I work with single celled eukaryotic algae.  While they don't seem to usually splice their transcripts, they are riddled with paralogs which they transcribe. I'd like to use this method to compare paralogs by treating them the same as splice variants. Do you see any problems with this?

Cheers!

**Comment by Quarkins** [comment]
Hi,
Thanks for your interest, sorry for the ridiculously slow response. I hope you went ahead and tested your idea, i don't see any problems so it should have worked out ok.
