### ISSUE TITLE
Question: supertranscripts (conceptual question)

### ISSUE THREAD

**Issue by sofiapar265** [Oshlack/Lace#36]
I have a more conceptual question. I have used Lace to create the reference SuperTranscript from de novo assembly in order to call variants between 2 individuals reared under 2 conditions (4 samples/4 libraries/4 vcf files). Reads used for calling SNPs were the same used for the de novo assembly, which was performed by trinity. 
I would like to ask you why only heterozygous SNPs, which are defined as those with at least one read supporting the reference allele, should be further Analysed? I thought that homozygous SNPs would have been more informative to me as I want to detect any differences between the 2 strains. 
Are these heterozygous SNPs those that are represented by GT:0/1 in the vcf files?

Thanks! Sofia

**Comment by nadiadavidson** [comment]
Sorry I missed this question last year (was on maternity leave)! Will answer now for future reference.

If you have multiple samples you can definitely try to call homozygous SNPs. The case where you can't call homozygous SNPs is when you only have a single sample. The reference you assemble will include the SNP, so it won't be possible to detect a difference against mapped reads.
