### ISSUE TITLE
Raise error when networkx version is too high

### ISSUE THREAD

**Issue by sarahhp** [Oshlack/Lace#43]
I noticed during my use of Lace that when I included networkx v2 in my conda enviornment it ran without error and created an incorrect superTranscriptome where all "whirl" counts were set to 0 and no case change occcured in the sequences.  

It would be helpful to raise this error at runtime so that new users can identify this and adjust their environment setup accordingly (especially since many other programs require networkx v2).

**Comment by nadiadavidson** [comment]
Thanks Sarah, we will hopefully make another version of Lace sortly which is compatible with networkx v2 as I know most people have this installed now.

**Comment by sarahhp** [comment]
That is good to hear!

**Comment by nadiadavidson** [comment]
Just letting you know that after a few minor modifications to the current dev version of code it runs for me with networkx v2, so feel free to try this out and report any issues to find.
