### ISSUE TITLE
-1 Transcripts and Whirls for some gene entries

### ISSUE THREAD

**Issue by sarahhp** [Oshlack/Lace#45]
This newest version of Lace (including commenting out the print_exception line) returns a file where some sequences have a -1 count for transcripts and whirls.  This seems unusual.

**Comment by nadiadavidson** [comment]
Hi Sarah,
The -1 indicates that the superTranscript construction failed because the splicing graph was too complex. In this case the longest transcript is reported. I will update our wiki documentation to explain.
Cheers,
Nadia.

**Comment by sarahhp** [comment]
Ah that makes sense.  Thanks for the explanation Nadia
