### ISSUE TITLE
Does a cluster mean a unigene or transcript?

### ISSUE THREAD

**Issue by wang-tianpeng** [Oshlack/Lace#47]
Does the cluster sequence in "SuperDuper.fasta" file mean a unigene?  If it is, Can I do the regular non-model species transcriptome pipeline analysis? I mean, annotate these cluster genes(unigenes) and do downstream differential expression analysis?

**Comment by nadiadavidson** [comment]
Sorry, very late reply but I'll post the answer before closing.

I'm not sure the superTranscripts are unigenes exactly, what they are is a sequence for each gene that includes all exons of that gene. Often they will be the longest transcript, but not always. You can use them for downstream analysis like you would for a model organism, replacing the genome with the SuperDuper.fasta file. In some cases you might be able to follow the non-model pipeline, but that would depend on the pipeline, in general you probably shouldn't.
