### ISSUE TITLE
(installation) In environment.yml, fix Python Version

### ISSUE THREAD

**Issue by lmuenter** [Oshlack/Lace#54]
Sadly, networkx 2.3 clashes with Python 3.9, since fractions.gcd() has been migrated to math.gcd(). Because of that, running Lace following installation causes an error:

```
ImportError: cannot import name 'gcd' from 'fractions'
```

Fixing the version of Python in `Lace-1.14.1/environment.yml` fixes this problem. I tried Python=3.5, and now it works.

**Comment by nadiadavidson** [comment]
Thanks. We had this fixed in the master branch, but hadn't made a new release with it.

Cheers,
Nadia.
